name: 'rcmcarddav-ci-setup'
description: 'Setup RCMCardDAV test environment'
inputs:
  php-version:
    description: 'PHP version to use'
    required: true
    default: '8.0'
runs:
  using: "composite"
  steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer:v2
          extensions: gd, xdebug, curl
          coverage: xdebug
      - name: Checkout roundcubemail
        uses: actions/checkout@v2
        with:
          path: roundcubemail
          repository: mstilkerich/roundcubemail
          ref: 'rcmcarddav_ci'
      - name: Install dependencies
        run: composer update --no-interaction --no-progress
