language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.5.11
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

script:
  - phpunit --configuration tests/phpunit.xml

before_script: composer install
