language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true

script:
  - phpunit --configuration tests/phpunit.xml
  - ./bin/phpcs -p --standard=tests/phpcs/ruleset.xml lib/


before_script: composer install
