#!/usr/bin/env php
<?php

// Replace namespaces in cov files generated by PHPUnit PHAR so they are parseable
// PHPCov PHAR
// See https://github.com/sebastianbergmann/phpcov/issues/109

$script = array_shift($argv);
if (count($argv) < 1) {
    echo "Usage: $script coverage.cov [coverage2.cov ...]\n";
    exit(1);
}

foreach ($argv as $covfile) {
    $content = file_get_contents($covfile);
    if ($content === false) {
        echo "Failed to read $covfile\n";
        exit(1);
    }

    $content = preg_replace_callback(
        "#\:(\d+)\:\"(.?)PHPUnit\\\SebastianBergmann\\\#",
        function($matches): string {
            $hasNull = strlen($matches[2]) === 1;
            $size = $matches[1];
            $size -= 8;

            if ($hasNull) {
                return sprintf(":%d:\"\0SebastianBergmann\\", $size);
            }

            return sprintf(':%d:"SebastianBergmann\\', $size);
        }, $content);

    if (file_put_contents($covfile, $content) === false) {
        echo "Failed to write $covfile\n";
        exit(1);
    }
}
