ALTER TABLE TABLE_PREFIXcarddav_groups MODIFY `vcard` LONGTEXT DEFAULT NULL;
ALTER TABLE TABLE_PREFIXcarddav_groups MODIFY `etag`  VARCHAR(255) DEFAULT NULL;
ALTER TABLE TABLE_PREFIXcarddav_groups MODIFY `cuid`  VARCHAR(255) DEFAULT NULL;
ALTER TABLE TABLE_PREFIXcarddav_groups MODIFY `uri`   VARCHAR(255) DEFAULT NULL;

UPDATE TABLE_PREFIXcarddav_groups SET `vcard`=NULL,`etag`=NULL,`uri`=NULL,`cuid`=NULL WHERE `etag` LIKE 'dummy%';
