ALTER TABLE TABLE_PREFIXcarddav_groups ALTER COLUMN vcard DROP NOT NULL;
ALTER TABLE TABLE_PREFIXcarddav_groups ALTER COLUMN etag  DROP NOT NULL;
ALTER TABLE TABLE_PREFIXcarddav_groups ALTER COLUMN cuid  DROP NOT NULL;
ALTER TABLE TABLE_PREFIXcarddav_groups ALTER COLUMN uri   DROP NOT NULL;

UPDATE TABLE_PREFIXcarddav_groups SET vcard=NULL,etag=NULL,uri=NULL,cuid=NULL WHERE etag LIKE 'dummy%';

