<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Aktivovat adresář kontaktů CardDAV",
	'cd_newabboxtitle'=> "Přidat nový adresář kontaktů CardDAV",
	'cd_username'=> "Uživatel",
	'cd_password'=> "Heslo",
	'cd_url'=> "URL",
	'cd_name'=> "Název adresáře kontaktů CardDAV",
	'cd_delete'=> "Odstranit tento adresář kontaktů",
	'cd_name_new'=> "Nastavit nový adresář kontaktů",
	'cd_refresh_time'=> "Interval aktualizace (hodiny)",
	'cd_err_noabfound'=> "no addressbook found",
);
?>
