<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "CardDAV-Adressbuch aktivieren",
	'cd_newabboxtitle'=> "Neues Adressbuch hinzuf&uuml;gen",
	'cd_username'=> "Benutzername",
	'cd_password'=> "Passwort",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "Ihre PHP Version ist zu alt! Es wird mindestens 5.3.0 benoetigt! Sie haben folgende Version installiert:",
	'cd_name'=> "Name des Adressbuches",
	'cd_delete'=> "Dieses Adressbuch entfernen",
	'cd_name_new'=> "Neues Adressbuch konfigurieren",
	'cd_displayorder'=> "Namens-Darstellung",
	'cd_sortorder'=> "Sortierschlüssel",
	'cd_refresh_time'=> "Aktualisierungsintervall (Stunden)",
);
?>
