<?php
$labels['cd_title'] = 'CardDAV';
$labels['cd_active'] = 'CardDAV-Adressbuch aktivieren';
$labels['cd_username'] = 'Benutzername';
$labels['cd_password'] = 'Passwort';
$labels['cd_url'] = 'URL';
$labels['cd_php_too_old'] = "Ihre PHP Version ist zu alt! Es wird mindestens 5.3.0 benoetigt! Sie haben folgende Version installiert:";
$labels['cd_name'] = "Name des Adressbuches";
$labels['cd_delete'] = "Dieses Adressbuch entfernen";
$labels['cd_name_new'] = "Neues Adressbuch konfigurieren";
$labels['cd_displayorder'] = "Namens-Darstellung";
$labels['cd_sortorder'] = "Sortierschlüssel";
$labels['cd_refresh_time'] = "Aktualisierungsintervall (Stunden)";
?>
