<?php
$labels['cd_title'] = 'CardDAV';
$labels['cd_use_carddav'] = 'Activate CardDAV-Addressbook';
$labels['cd_username'] = 'Username';
$labels['cd_password'] = 'Password';
$labels['cd_url'] = 'URL';
$labels['cd_lax_resource_checking'] = 'Lax resource checking. Activate this option if your addressbooks are not showing up.';
$labels['cd_php_too_old'] = "Your version of PHP is too old! Please update to at least 5.3.0! You got the following version installed:";
$labels['cd_description'] = "Name of the addressbook";
$labels['cd_delete'] = "Remove this addressbook";
$labels['cd_description_new'] = "Configure new addressbook";
$labels['cd_displayorder'] = "Display order";
$labels['cd_sortorder'] = "Sort order";
$labels['cd_refresh_time'] = "Update interval (hours)";
?>
