<?php
$labels = Array(
	'cd_title' => 'CardDAV',
	'cd_active' => 'Activate CardDAV-Addressbook',
	'cd_username' => 'Username',
	'cd_password' => 'Password',
	'cd_url' => 'URL',
	'cd_php_too_old' => "Your version of PHP is too old! Please update to at least 5.3.0! You got the following version installed:",
	'cd_name' => "Name of the addressbook",
	'cd_delete' => "Remove this addressbook",
	'cd_name_new' => "Configure new addressbook",
	'cd_displayorder' => "Display order",
	'cd_sortorder' => "Sort order",
	'cd_refresh_time' => "Update interval (hours)",
);
?>
