<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Activar Libreta de Direcciones CardDAV",
	'cd_newabboxtitle'=> "Añadir nueva Libreta de Direcciones",
	'cd_username'=> "Nombre de usuario",
	'cd_password'=> "Contraseña",
	'cd_url'=> "URL",
	'cd_name'=> "Nombre de la libreta de direcciones",
	'cd_delete'=> "Eliminar esta libreta de direcciones",
	'cd_name_new'=> "Configurar una nueva libreta de direcciones",
	'cd_refresh_time'=> "Intervalo de actualización (horas)",
	'cd_err_noabfound'=> "libreta de direcciones no encontrada",
);
?>
