<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Activar Libreta de Direcciones CardDAV",
	'cd_newabboktitle'=> "Añadir nueva Libreta de Direcciones",
	'cd_username'=> "Nombre de usuario",
	'cd_password'=> "Contraseña",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "La versión de PHP es demasiado antigua! Por favor, actualiza al menos a la 5.3.0! La versión instalada es la siguiente:",
	'cd_name'=> "Nombre de la libreta de direcciones",
	'cd_delete'=> "Eliminar esta libreta de direcciones",
	'cd_name_new'=> "Configurar una nueva libreta de direcciones",
	'cd_displayorder'=> "Orden de Visualización",
	'cd_sortorder'=> "Orden de clasificación",
	'cd_refresh_time'=> "Intervalo de actualización (horas)",
	'cd_err_noabfound' => 'no addressbook found',
);
?>
