<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Activer CardDAV-Addressbook",
	'cd_username'=> "Nom d'utilisateur",
	'cd_password'=> "Mot de passe",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "Votre version de PHP est trop veille! Merci de la mettre à jour avec la version 5.3.0 au minimum! Vous avez la version suivante d'installé:",
	'cd_name'=> "Nom du carnet d'adresses",
	'cd_delete'=> "Supprimer ce carnet d'adresses",
	'cd_name_new'=> "Ajouter un nouveau carnet d'adresses",
	'cd_displayorder'=> "Afficher par",
	'cd_sortorder'=> "Ordre de tri",
	'cd_refresh_time'=> "Validité du cache local (en heures)",
);
?>
