<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Activer ce carnet d'adresses",
	'cd_newabboxtitle'=> "Ajouter un nouveau carnet d'adresses",
	'cd_username'=> "Nom d'utilisateur",
	'cd_password'=> "Mot de passe",
	'cd_url'=> "URL",
	'cd_name'=> "Nom du carnet d'adresses",
	'cd_use_categories' => "Utilise les categories comme des groupes",
	'cd_delete'=> "Supprimer ce carnet d'adresses",
	'cd_name_new'=> "Ajouter un nouveau carnet d'adresses",
	'cd_refresh_time'=> "Validité du cache local (en heures)",
	'cd_err_noabfound'=> "Aucun carnet d'adresses trouvé",
	'cd_enabled'=>'Activé',
	'cd_disabled'=>'Désactivé',
	'cd_lastupdate_time'=>'Dernière mise-à-jour',
	'cd_resync' => "Forcer la synchronisation immédiate avec le serveur",
	'cd_msg_synchronized' => 'Le carnet d\'adresses $name a été synchronisé (Cela a duré $duration secondes)',
	'cd_msg_syncfailed' => 'La synchronisation du carnet d\'adresses $name a échoué: $errormsg',
	'cd_frompreset' => ' (à partir du préréglage _PRESETNAME_)',
);
?>
