<?php
$labels = Array(
	'cd_title' => 'CardDAV',
	'cd_active'=> "CardDAV címjegyzék aktiválása",
	'cd_newabboxtitle'=> "Új címjegyzék hozzáadása",
	'cd_username'=> "Felhasználónév",
	'cd_password'=> "Jelszó",
	'cd_url'=> "URL",
	'cd_name'=> "Címjegyzék neve",
	'cd_use_categories' => "Használja a CATEGORIES a KIND=group (RFC6350) helyett\namikor új kapcsolati csoportot hoz létre",
	'cd_delete'=> "Címjegyzék törlése",
	'cd_name_new'=> "Címjegyzék beállításai",
	'cd_refresh_time'=> "Frissítési intervallum (óra)",
	'cd_err_noabfound'=> "nem található címjegyzék",
	'cd_enabled' => 'Engedélyezett',
	'cd_disabled' => 'Tiltott',
	'cd_lastupdate_time'=>'Utolsó frissítés ideje',
	'cd_resync' => "Azonnali szinkronizálás a szerverrel",
	'cd_msg_synchronized' => 'A $name CardDAV címjegyzék szinkronizálva lett ($duration másodperc alatt)',
	'cd_msg_syncfailed' => 'A $name CardDAV címjegyzék hibára futott: $errormsg',
	'cd_frompreset' => ' (a _PRESETNAME_ sablon alapján)',
);
?>
