<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "CardDAV címjegyzék aktiválása",
	'cd_newabboktitle'=> "Add new Addressbook",
	'cd_username'=> "Felhasználónév",
	'cd_password'=> "Jelszó",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "A PHP verziód túl régi, e program futásához legalább 5.3.0-ás verzióra van szükség. A jelenlegi PHP verzió:",
	'cd_name'=> "Címjegyzék neve",
	'cd_delete'=> "Címjegyzék törlése",
	'cd_name_new'=> "Címjegyzék beállításai",
	'cd_displayorder'=> "Névjegyek megjelenítési rendje",
	'cd_sortorder'=> "Rendezési sorrend ",
	'cd_refresh_time'=> "Frissítési intervallum (óra)",
	'cd_err_noabfound' => 'no addressbook found',
);
?>
