<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "CardDAV címjegyzék aktiválása",
	'cd_newabboxtitle'=> "Add new addressbook",
	'cd_username'=> "Felhasználónév",
	'cd_password'=> "Jelszó",
	'cd_url'=> "URL",
	'cd_name'=> "Címjegyzék neve",
	'cd_delete'=> "Címjegyzék törlése",
	'cd_name_new'=> "Címjegyzék beállításai",
	'cd_refresh_time'=> "Frissítési intervallum (óra)",
	'cd_err_noabfound'=> "no addressbook found",
);
?>
