<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Aktifkan buku alamat berbasis CardDAV",
	'cd_newabboxtitle'=> "Add new Addressbook",
	'cd_username'=> "Nama pengguna",
	'cd_password'=> "Kata sandi",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "Versi PHP yang digunakan adalah versi yang terlalu tua! Mohon di-update sedikitnya ke versi 5.3.0! Versi PHP yang digunakan oleh Anda:",
	'cd_name'=> "Nama buku alamat",
	'cd_delete'=> "Menghapuskan buku alamat ini",
	'cd_name_new'=> "Mengkonfigurasi buku alamat baru",
	'cd_displayorder'=> "Urutan tampilan",
	'cd_sortorder'=> "Urutan penyortiran",
	'cd_refresh_time'=> "Interval update (dalam jam)",
	'cd_err_noabfound' => 'no addressbook found',
);
?>
