<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Aktifkan buku alamat berbasis CardDAV",
	'cd_newabboxtitle'=> "Add new addressbook",
	'cd_username'=> "Nama pengguna",
	'cd_password'=> "Kata sandi",
	'cd_url'=> "URL",
	'cd_name'=> "Nama buku alamat",
	'cd_delete'=> "Menghapuskan buku alamat ini",
	'cd_name_new'=> "Mengkonfigurasi buku alamat baru",
	'cd_refresh_time'=> "Interval update (dalam jam)",
	'cd_err_noabfound'=> "no addressbook found",
);
?>
