<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Utilizza rubrica CardDAV",
	'cd_username'=> "Nome utente",
	'cd_password'=> "Password",
	'cd_url'=> "Indirizzo server (URL)",
	'cd_php_too_old'=> "E' necessario aggiornare PHP alla versione 5.3.0 o superiore! Attualmente hai la versione:",
	'cd_name'=> "Nome nuova rubrica",
	'cd_delete'=> "Elimina rubrica",
	'cd_name_new'=> "Crea una nuova rubrica",
	'cd_displayorder'=> "Disposizione",
	'cd_sortorder'=> "Ordinamento",
	'cd_refresh_time'=> "Frequenza di aggiornamento (ore)",
);
?>
