<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Utilizza rubrica CardDAV",
	'cd_newabboxtitle'=> "Aggiungi una nuova Rubrica",
	'cd_username'=> "Nome utente",
	'cd_password'=> "Password",
	'cd_url'=> "Indirizzo server (URL)",
	'cd_name'=> "Nome nuova rubrica",
	'cd_delete'=> "Elimina rubrica",
	'cd_name_new'=> "Crea una nuova rubrica",
	'cd_refresh_time'=> "Frequenza di aggiornamento (ore)",
	'cd_err_noabfound'=> "Nessuna Rubrica Trovata",
);
?>
