<?php
$labels['cd_title'] = 'CardDAV';
$labels['cd_active'] = 'Utilizza rubrica CardDAV';
$labels['cd_username'] = 'Nome utente';
$labels['cd_password'] = 'Password';
$labels['cd_url'] = 'Indirizzo server (URL)';
$labels['cd_php_too_old'] = "E' necessario aggiornare PHP alla versione 5.3.0 o superiore! Attualmente hai la versione:";
$labels['cd_name'] = "Nome nuova rubrica";
$labels['cd_delete'] = "Elimina rubrica";
$labels['cd_name_new'] = "Crea una nuova rubrica";
?>
