<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Aktywuj książkę adresową CardDAV",
	'cd_newabboktitle'=> "Add new Addressbook",
	'cd_username'=> "Nazwa użytkownika",
	'cd_password'=> "Hasło",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "Twoja wersja PHP jest nieaktualna! Proszę zaktualizuj do minimum wersji 5.3.0! Twoja wersja to:",
	'cd_name'=> "Nazwa książki adresowej",
	'cd_delete'=> "Usuń książkę adresową",
	'cd_name_new'=> "Konfiguracja nowej książki adresowej",
	'cd_displayorder'=> "Kolejność wyświetlania",
	'cd_sortorder'=> "Kolejność sortowania",
	'cd_refresh_time'=> "Interwał aktualizacji (godziny)",
	'cd_err_noabfound' => 'no addressbook found',
);
?>
