<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Активировать адресную книгу CardDAV",
	'cd_newabboxtitle'=> "Добавить новую адресную книгу",
	'cd_username'=> "Имя пользователя",
	'cd_password'=> "Пароль",
	'cd_url'=> "URL",
	'cd_name'=> "Название адресной книги",
	'cd_delete'=> "Удалить адресную книгу",
	'cd_name_new'=> "Настроить новую адресную книгу",
	'cd_refresh_time'=> "Частота обновления (часов)",
	'cd_err_noabfound'=> "Не найдено ни одной адресной книги",
);
?>
