<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Aktivera CardDAV-adressboken",
	'cd_username'=> "Användarnamn",
	'cd_password'=> "Lösenord",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "Din version av PHP är för gammal! Vänligen uppdatera till åtminstone 5.0.3! Du har följande version installerad: ",
	'cd_name'=> "Namn på adressboken",
	'cd_delete'=> "Radera denna adressbok",
	'cd_name_new'=> "Konfigurera en ny addressbok",
	'cd_displayorder'=> "Visningsföljd",
	'cd_sortorder'=> "Sorteringsordning",
	'cd_refresh_time'=> "Uppdateringsintervall (timmar)",
);
?>
