<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Увімкнути список контактів CardDAV",
	'cd_newabboxtitle'=> "Додати новий список контактів",
	'cd_username'=> "Ім'я користувача",
	'cd_password'=> "Пароль",
	'cd_url'=> "URL",
	'cd_name'=> "Назва списку контактів",
	'cd_delete'=> "Видалити цей список контактів",
	'cd_name_new'=> "Налаштувати цей список контактів",
	'cd_refresh_time'=> "Період оновлення (в годинах)",
	'cd_err_noabfound'=> "не знайдено жодного списку контактів",
);
?>
